apiVersion: v1
kind: Secret
metadata:
  name: {{ template "apply-for-legalaid.fullname" . }}
type: Opaque
data:
  deployHost: {{ .Values.deploy.host | b64enc | quote }}
  secretKey: {{ .Values.deploy.secretKey | b64enc | quote }}
  railsMasterKey: {{ .Values.deploy.rails_master_key | b64enc | quote }}
  postgresDatabase: {{ .Values.postgresql.postgresDatabase | b64enc | quote }}
  postgresUser: {{ .Values.postgresql.postgresUser | b64enc | quote }}
  postgresPassword: {{ .Values.postgresql.postgresPassword | b64enc | quote }}
  sentryDsn: {{ .Values.sentry.dsn | b64enc | quote }}
  govukNotifyApiKey: {{ .Values.govuk_notify.api_key | b64enc | quote }}
  govukNotifyEnv: {{ .Values.govuk_notify.environment | b64enc | quote }}
  ordnanaceSurveyApiKey: {{ .Values.ordnanace_survey.api_key | b64enc | quote }}
