require: rubocop-performance

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
  - 'db/schema.rb'
  - 'vendor/**/*'
  - 'node_modules/**/*'
  - 'ccms_integration/*'

Lint/AmbiguousBlockAssociation:
  Exclude:
  - 'spec/**/*'

Lint/UriEscapeUnescape:
  Enabled: false

Lint/RedundantCopDisableDirective:
  Enabled: false

Metrics/AbcSize:
  Exclude:
  - 'db/migrate/*'
  - 'ccms_integration/helpers/ccms_payload_analyser.rb'

Metrics/BlockLength:
  Exclude:
  - 'config/routes.rb'
  - 'spec/**/*'

Metrics/MethodLength:
  Exclude:
  - 'db/migrate/*'
  - 'ccms_integration/helpers/ccms_payload_analyser.rb'
  - 'spec/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Metrics/ParameterLists:
  Max: 6

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/Documentation:
  Exclude:
  - '**/*'

Style/SymbolArray:
  EnforcedStyle: percent

Style/Lambda:
  EnforcedStyle: literal

Style/RegexpLiteral:
  Enabled: false
