version: '3'

services:
  postgres:
    image: postgres:10.5
    volumes:
    - pgdata:/var/lib/postgresql/data
  clamav:
    image: 926803513772.dkr.ecr.eu-west-1.amazonaws.com/laa-apply-for-legal-aid/clamav:1.0.0
    ports:
    - "3310:3310"
  api:
    environment:
    - DB_HOST=postgres
    build: .
    command: bin/run
    ports:
    - "3002:3002"
    depends_on:
    - postgres
    - clamav

volumes:
  pgdata:
