version: '3'

services:
  postgres:
    image: postgres:10.5
    volumes:
    - pgdata:/var/lib/postgresql/data
  api:
    environment:
    - DB_HOST=postgres
    build: .
    command: bin/run
    ports:
    - "3002:3002"
    depends_on:
    - postgres

volumes:
  pgdata:
