version: 2.0

references:

  build_containers_config: &build_container_config
    docker:
    - image: circleci/ruby:2.5.1
      environment:
        GITHUB_TEAM_NAME_SLUG: apply-for-legalaid
    - image: postgres:10.5

  build_docker_image: &build_docker_image
    run:
      name: Build laa-apply-for-legalaid-api  docker image
      command: docker build -t app .

jobs:
  build_and_test:
    <<: *build_container_config
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: Install gems
        command: bundle install
    - run: sudo apt install -y postgresql-client || true
    - run:
        name: Database Setup
        command: |
          bundle exec rake db:setup
          bundle exec rake db:migrate
    - run:
        name: Run Tests
        command: bundle exec rake
    - *build_docker_image


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_test



          