version: 2.0

references:

  build_containers_config: &build_container_config
    docker:
    - image: circleci/ruby:2.5.1
      environment:
        GITHUB_TEAM_NAME_SLUG: apply-for-legalaid
    - image: postgres:10.5

  setup_test_env: &setup_test_env
    run:
      name: Setup aws on debian environment
      command: |
        sudo apt-get --assume-yes install python3-pip
        sudo pip3 install awscli
        $(aws ecr get-login --region eu-west-1 --no-include-email)

  build_docker_image: &build_docker_image
    run:
      name: Build laa-apply-for-legalaid-api  docker image
      command: docker build -t app .

  push_to_ecr: &push_to_ecr
    run:
      name: Push image to ecr repo
      command: |
        docker tag app "${ECR_ENDPOINT}/${GITHUB_TEAM_NAME_SLUG}/${REPO_NAME}:${CIRCLE_SHA1}"
        docker push "${ECR_ENDPOINT}/${GITHUB_TEAM_NAME_SLUG}/${REPO_NAME}:${CIRCLE_SHA1}"

        if [ "${CIRCLE_BRANCH}" == "master" ]; then
          docker tag app "${ECR_ENDPOINT}/${GITHUB_TEAM_NAME_SLUG}/${REPO_NAME}:latest"
          docker push "${ECR_ENDPOINT}/${GITHUB_TEAM_NAME_SLUG}/${REPO_NAME}:latest"
        fi

jobs:
  build_and_test:
    <<: *build_container_config
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - *setup_test_env
    - restore_cache:
        keys:
          - laa-apply-for-legalaid-api-{{ checksum "Gemfile.lock" }}
          - laa-apply-for-legalaid-api

    - run:
        name: Bundle Install
        command: bundle check || bundle install

      # Store bundle cache
    - save_cache:
        key: laa-apply-for-legalaid-api-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
    - run: sudo apt install -y postgresql-client || true
    - run:
        name: Database Setup
        command: |
          bundle exec rake db:setup
          bundle exec rake db:migrate
    - run:
        name: Run Tests
        command: bundle exec rake
    - *build_docker_image
    - *push_to_ecr


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_test



          