---
proceeding_merits:
  ACTION_DAMAGES_AGAINST_POLICE:
    generate_block?: true
    value: false

property_means:
  ADDPROPERTY_INPUT_B_4WP2_18A:
    value: false
    br100_meaning: 'Add. Property: Owned with 3rd party, inc ex. partner?'
    response_type: boolean
    user_defined: false
    generate_block?: true
  ADDPROPERTY_INFER_B_4WP2_52A:
    value: false
    br100_meaning: 'Add. Property: SMOD?'
    response_type: boolean
    user_defined: false
    generate_block?: true
  ADDPROPERTY_INPUT_B_4WP2_24A:
    value: false
    br100_meaning: 'Add. Property: Subject to restraint (freezing) order?'
    response_type: boolean
    user_defined: false
    generate_block?: true
  ADDPROPERTY_INPUT_B_4WP2_25A:
    value: false
    br100_meaning: 'Add. Property: Subject to bankruptcy?'
    response_type: boolean
    user_defined: false
    generate_block?: true
  ADDPROPERTY_INPUT_B_4WP2_26A:
    value: false
    br100_meaning: 'Add. Property: SMOD in other proceedings?'
    response_type: boolean
    user_defined: false
    generate_block?: true
  ADDPROPERTY_INPUT_B_4WP2_27A:
    value: false
    br100_meaning: 'Add. Property: Subject to foreign exchange controls?'
    response_type: boolean
    user_defined: false
    generate_block?: true
  ADDPROPERTY_INPUT_B_4WP2_28A:
    value: false
    br100_meaning: 'Add. Property: Subject to possession proceedings?'
    response_type: boolean
    user_defined: false
    generate_block?: true
  ADDPROPERTY_INPUT_B_4WP2_32A:
    value: false
    br100_meaning: 'Add. Property: Client/Partner has a deferred interest?'
    response_type: boolean
    user_defined: false
    generate_block?: true

