apiVersion: v1
kind: Service
metadata:
  name: {{ template "apply-for-legal-aid.fullname" . }}
  labels:
    app: {{ template "apply-for-legal-aid.name" . }}
    chart: {{ template "apply-for-legal-aid.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 9394
      targetPort: 9394
      name: metrics
  selector:
    app: {{ template "apply-for-legal-aid.name" . }}
    release: {{ .Release.Name }}
