---
http_interactions:
- request:
    method: post
    uri: http://localhost:3000/assessments
    body:
      encoding: UTF-8
      string: '{"client_reference_id":"L-BH3-YY7","submission_date":"2020-03-05","matter_proceeding_type":"domestic_abuse"}'
    headers:
      User-Agent:
      - Faraday v0.17.3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Content-Type:
      - application/json; charset=utf-8
      Etag:
      - W/"b48da7b6597e23bfa89c4286c28f2464"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 56590d66-a5e2-43ec-a2c1-56ace8c03f1f
      X-Runtime:
      - '0.027647'
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: '{"success":true,"objects":[{"id":"3d5be5c1-6b36-4f29-be54-4b3c267931fa","client_reference_id":"L-BH3-YY7","remote_ip":{"family":30,"addr":1,"mask_addr":340282366920938463463374607431768211455},"created_at":"2020-03-05T11:53:28.596Z","updated_at":"2020-03-05T11:53:28.596Z","submission_date":"2020-03-05","matter_proceeding_type":"domestic_abuse","assessment_result":"pending"}],"errors":[]}'
    http_version: null
  recorded_at: Thu, 05 Mar 2020 11:53:28 GMT
- request:
    method: post
    uri: http://localhost:3000/assessments/3d5be5c1-6b36-4f29-be54-4b3c267931fa/applicant
    body:
      encoding: UTF-8
      string: '{"applicant":{"date_of_birth":"1980-01-10","involvement_type":"applicant","has_partner_opponent":false,"receives_qualifying_benefit":true}}'
    headers:
      User-Agent:
      - Faraday v0.17.3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Content-Type:
      - application/json; charset=utf-8
      Etag:
      - W/"3aa91f8f693c6076d05ccd5b34d1f500"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - e944f789-e16c-4a60-895c-9bdac50ea4df
      X-Runtime:
      - '0.010345'
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: '{"objects":[{"id":"981e3d45-dcc5-45b3-87f5-07f010bc3b18","assessment_id":"3d5be5c1-6b36-4f29-be54-4b3c267931fa","date_of_birth":"1980-01-10","involvement_type":"applicant","has_partner_opponent":false,"receives_qualifying_benefit":true,"created_at":"2020-03-05T11:53:28.624Z","updated_at":"2020-03-05T11:53:28.624Z","self_employed":false}],"errors":[],"success":true}'
    http_version: null
  recorded_at: Thu, 05 Mar 2020 11:53:28 GMT
- request:
    method: post
    uri: http://localhost:3000/assessments/3d5be5c1-6b36-4f29-be54-4b3c267931fa/capitals
    body:
      encoding: UTF-8
      string: '{"bank_accounts":[{"description":"Money not in a bank account","value":"10000.0"}],"non_liquid_capital":[{"description":"Land","value":"50000.0"}]}'
    headers:
      User-Agent:
      - Faraday v0.17.3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Content-Type:
      - application/json; charset=utf-8
      Etag:
      - W/"6067cbb55c38548f967c13f9c7915722"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - ce3b1919-3e9c-4daf-8383-db435455ef58
      X-Runtime:
      - '0.012541'
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: '{"objects":{"id":"2272f686-571b-4091-b296-8c5df8c678e8","assessment_id":"3d5be5c1-6b36-4f29-be54-4b3c267931fa","total_liquid":"0.0","total_non_liquid":"0.0","total_vehicle":"0.0","total_property":"0.0","total_mortgage_allowance":"0.0","total_capital":"0.0","pensioner_capital_disregard":"0.0","assessed_capital":"0.0","capital_contribution":"0.0","lower_threshold":"0.0","upper_threshold":"0.0","assessment_result":"pending","created_at":"2020-03-05T11:53:28.599Z","updated_at":"2020-03-05T11:53:28.599Z"},"errors":[],"success":true}'
    http_version: null
  recorded_at: Thu, 05 Mar 2020 11:53:28 GMT
- request:
    method: post
    uri: http://localhost:3000/assessments/3d5be5c1-6b36-4f29-be54-4b3c267931fa/vehicles
    body:
      encoding: UTF-8
      string: '{"vehicles":[]}'
    headers:
      User-Agent:
      - Faraday v0.17.3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Content-Type:
      - application/json; charset=utf-8
      Etag:
      - W/"7eb7dee5a8f69a7b4580e1e2bd9fa86a"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 1831eb63-3f2a-4fd9-8c36-a3c4352865ac
      X-Runtime:
      - '0.004953'
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: '{"vehicles":[],"errors":[],"success":true}'
    http_version: null
  recorded_at: Thu, 05 Mar 2020 11:53:28 GMT
- request:
    method: post
    uri: http://localhost:3000/assessments/3d5be5c1-6b36-4f29-be54-4b3c267931fa/properties
    body:
      encoding: UTF-8
      string: '{"properties":{"main_home":{"value":"200000.0","outstanding_mortgage":"100000.0","percentage_owned":"50.0","shared_with_housing_assoc":false},"additional_properties":[{"value":0,"outstanding_mortgage":0,"percentage_owned":0,"shared_with_housing_assoc":false}]}}'
    headers:
      User-Agent:
      - Faraday v0.17.3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Content-Type:
      - application/json; charset=utf-8
      Etag:
      - W/"c4758962d00f280a401c17fd7224faf4"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 7e626553-83b6-4a7f-88be-e6042103d4e1
      X-Runtime:
      - '0.012989'
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: '{"objects":[{"id":"cd5c8227-f909-46f1-8535-edfcb5640916","value":"200000.0","outstanding_mortgage":"100000.0","percentage_owned":"50.0","main_home":true,"shared_with_housing_assoc":false,"created_at":"2020-03-05T11:53:28.679Z","updated_at":"2020-03-05T11:53:28.679Z","capital_summary_id":"2272f686-571b-4091-b296-8c5df8c678e8","transaction_allowance":"0.0","allowable_outstanding_mortgage":"0.0","net_value":"0.0","net_equity":"0.0","assessed_equity":"0.0","main_home_equity_disregard":"0.0"},{"id":"acfd1ed9-865b-4680-b682-e03ce19d7217","value":"0.0","outstanding_mortgage":"0.0","percentage_owned":"0.0","main_home":false,"shared_with_housing_assoc":false,"created_at":"2020-03-05T11:53:28.682Z","updated_at":"2020-03-05T11:53:28.682Z","capital_summary_id":"2272f686-571b-4091-b296-8c5df8c678e8","transaction_allowance":"0.0","allowable_outstanding_mortgage":"0.0","net_value":"0.0","net_equity":"0.0","assessed_equity":"0.0","main_home_equity_disregard":"0.0"}],"errors":[],"success":true}'
    http_version: null
  recorded_at: Thu, 05 Mar 2020 11:53:28 GMT
- request:
    method: get
    uri: http://localhost:3000/assessments/3d5be5c1-6b36-4f29-be54-4b3c267931fa
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.17.3
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Content-Type:
      - application/json; charset=utf-8
      Etag:
      - W/"ea7f29fa55fe6f3e0292ca8e57e55eb4"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 66ac5481-6f35-4de8-bfa3-a2ed4e1c09e0
      X-Runtime:
      - '0.034239'
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: '{"assessment_result":"contribution_required","applicant":{"receives_qualifying_benefit":true,"age_at_submission":40},"capital":{"total_liquid":"10000.0","total_non_liquid":"50000.0","pensioner_capital_disregard":"0.0","total_capital":"60000.0","capital_contribution":"57000.0","liquid_capital_items":[{"description":"Money
        not in a bank account","value":"10000.0"}],"non_liquid_capital_items":[{"description":"Land","value":"50000.0"}]},"property":{"total_mortgage_allowance":"100000.0","total_property":"0.0","main_home":{"value":"200000.0","transaction_allowance":"6000.0","allowable_outstanding_mortgage":"100000.0","shared_with_housing_assoc":false,"percentage_owned":"50.0","net_equity":"47000.0","main_home_equity_disregard":"100000.0","assessed_equity":"0.0"},"additional_properties":[{"value":"0.0","transaction_allowance":"0.0","allowable_outstanding_mortgage":"0.0","percentage_owned":"0.0","assessed_equity":"0.0"}]},"vehicles":{"total_vehicle":"0.0","vehicles":[]}}'
    http_version: null
  recorded_at: Thu, 05 Mar 2020 11:53:28 GMT
recorded_with: VCR 5.1.0
