---
http_interactions:
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments
    body:
      encoding: UTF-8
      string: '{"client_reference_id":"L-6U3-WMC","submission_date":"2020-03-05","matter_proceeding_type":"domestic_abuse"}'
    headers:
      User-Agent:
      - Faraday v0.17.3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - openresty/1.15.8.2
      Date:
      - Thu, 05 Mar 2020 15:38:16 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Etag:
      - W/"bcf14e905c75cab04f8125bfd93f442c"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - d5fa1ac4143d5df7ff65bea8283d563f
      X-Runtime:
      - '0.015014'
    body:
      encoding: ASCII-8BIT
      string: '{"success":true,"objects":[{"id":"9c64cbb7-d495-47fb-a896-ace91c4bc8ca","client_reference_id":"L-6U3-WMC","remote_ip":{"family":2,"addr":1377660346,"mask_addr":4294967295},"created_at":"2020-03-05T15:38:16.086Z","updated_at":"2020-03-05T15:38:16.086Z","submission_date":"2020-03-05","matter_proceeding_type":"domestic_abuse","assessment_result":"pending"}],"errors":[]}'
    http_version: null
  recorded_at: Thu, 05 Mar 2020 15:38:16 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/9c64cbb7-d495-47fb-a896-ace91c4bc8ca/applicant
    body:
      encoding: UTF-8
      string: '{"applicant":{"date_of_birth":"1980-01-10","involvement_type":"applicant","has_partner_opponent":false,"receives_qualifying_benefit":true}}'
    headers:
      User-Agent:
      - Faraday v0.17.3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - openresty/1.15.8.2
      Date:
      - Thu, 05 Mar 2020 15:38:16 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Etag:
      - W/"d20ae6581c4aebfc1ecc6b9ff844dc95"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 2ba0492fbcc7f109e0f320cbc5d608f5
      X-Runtime:
      - '0.028916'
    body:
      encoding: ASCII-8BIT
      string: '{"objects":[{"id":"73bdfa2a-b25c-4880-85f3-97f440aee807","assessment_id":"9c64cbb7-d495-47fb-a896-ace91c4bc8ca","date_of_birth":"1980-01-10","involvement_type":"applicant","has_partner_opponent":false,"receives_qualifying_benefit":true,"created_at":"2020-03-05T15:38:16.208Z","updated_at":"2020-03-05T15:38:16.208Z","self_employed":false}],"errors":[],"success":true}'
    http_version: null
  recorded_at: Thu, 05 Mar 2020 15:38:16 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/9c64cbb7-d495-47fb-a896-ace91c4bc8ca/capitals
    body:
      encoding: UTF-8
      string: '{"bank_accounts":[{"description":"Money not in a bank account","value":"10000.0"}],"non_liquid_capital":[{"description":"Land","value":"50000.0"}]}'
    headers:
      User-Agent:
      - Faraday v0.17.3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - openresty/1.15.8.2
      Date:
      - Thu, 05 Mar 2020 15:38:16 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Etag:
      - W/"25f519759f6439168f1bf7258e0cc00e"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - d95631bdb2c4b176d8909bff85289027
      X-Runtime:
      - '0.016651'
    body:
      encoding: ASCII-8BIT
      string: '{"objects":{"id":"487fd71b-7ea5-40c0-881a-43bc93f299b9","assessment_id":"9c64cbb7-d495-47fb-a896-ace91c4bc8ca","total_liquid":"0.0","total_non_liquid":"0.0","total_vehicle":"0.0","total_property":"0.0","total_mortgage_allowance":"0.0","total_capital":"0.0","pensioner_capital_disregard":"0.0","assessed_capital":"0.0","capital_contribution":"0.0","lower_threshold":"0.0","upper_threshold":"0.0","assessment_result":"pending","created_at":"2020-03-05T15:38:16.088Z","updated_at":"2020-03-05T15:38:16.088Z"},"errors":[],"success":true}'
    http_version: null
  recorded_at: Thu, 05 Mar 2020 15:38:16 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/9c64cbb7-d495-47fb-a896-ace91c4bc8ca/vehicles
    body:
      encoding: UTF-8
      string: '{"vehicles":[]}'
    headers:
      User-Agent:
      - Faraday v0.17.3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - openresty/1.15.8.2
      Date:
      - Thu, 05 Mar 2020 15:38:16 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Etag:
      - W/"7eb7dee5a8f69a7b4580e1e2bd9fa86a"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - aaac55cac5f85a72c4becb60ea8dc9f6
      X-Runtime:
      - '0.005441'
    body:
      encoding: ASCII-8BIT
      string: '{"vehicles":[],"errors":[],"success":true}'
    http_version: null
  recorded_at: Thu, 05 Mar 2020 15:38:16 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/9c64cbb7-d495-47fb-a896-ace91c4bc8ca/properties
    body:
      encoding: UTF-8
      string: '{"properties":{"main_home":{"value":"200000.0","outstanding_mortgage":"100000.0","percentage_owned":"50.0","shared_with_housing_assoc":false},"additional_properties":[{"value":0,"outstanding_mortgage":0,"percentage_owned":0,"shared_with_housing_assoc":false}]}}'
    headers:
      User-Agent:
      - Faraday v0.17.3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - openresty/1.15.8.2
      Date:
      - Thu, 05 Mar 2020 15:38:16 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Etag:
      - W/"7ace6929f92e54b09c95c9abd2041b67"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 78d634452cfef910939d82a386347301
      X-Runtime:
      - '0.044382'
    body:
      encoding: ASCII-8BIT
      string: '{"objects":[{"id":"17aad5f6-f1d6-43cb-9b12-82815a7555af","value":"200000.0","outstanding_mortgage":"100000.0","percentage_owned":"50.0","main_home":true,"shared_with_housing_assoc":false,"created_at":"2020-03-05T15:38:16.596Z","updated_at":"2020-03-05T15:38:16.596Z","capital_summary_id":"487fd71b-7ea5-40c0-881a-43bc93f299b9","transaction_allowance":"0.0","allowable_outstanding_mortgage":"0.0","net_value":"0.0","net_equity":"0.0","assessed_equity":"0.0","main_home_equity_disregard":"0.0"},{"id":"c102ccaa-d3e2-4415-b09b-59b2e5341a02","value":"0.0","outstanding_mortgage":"0.0","percentage_owned":"0.0","main_home":false,"shared_with_housing_assoc":false,"created_at":"2020-03-05T15:38:16.630Z","updated_at":"2020-03-05T15:38:16.630Z","capital_summary_id":"487fd71b-7ea5-40c0-881a-43bc93f299b9","transaction_allowance":"0.0","allowable_outstanding_mortgage":"0.0","net_value":"0.0","net_equity":"0.0","assessed_equity":"0.0","main_home_equity_disregard":"0.0"}],"errors":[],"success":true}'
    http_version: null
  recorded_at: Thu, 05 Mar 2020 15:38:16 GMT
- request:
    method: get
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/9c64cbb7-d495-47fb-a896-ace91c4bc8ca
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.17.3
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - openresty/1.15.8.2
      Date:
      - Thu, 05 Mar 2020 15:38:16 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Etag:
      - W/"ea7f29fa55fe6f3e0292ca8e57e55eb4"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - de2776e0271b6ea9b896ed882648e14b
      X-Runtime:
      - '0.143186'
    body:
      encoding: ASCII-8BIT
      string: '{"assessment_result":"contribution_required","applicant":{"receives_qualifying_benefit":true,"age_at_submission":40},"capital":{"total_liquid":"10000.0","total_non_liquid":"50000.0","pensioner_capital_disregard":"0.0","total_capital":"60000.0","capital_contribution":"57000.0","liquid_capital_items":[{"description":"Money
        not in a bank account","value":"10000.0"}],"non_liquid_capital_items":[{"description":"Land","value":"50000.0"}]},"property":{"total_mortgage_allowance":"100000.0","total_property":"0.0","main_home":{"value":"200000.0","transaction_allowance":"6000.0","allowable_outstanding_mortgage":"100000.0","shared_with_housing_assoc":false,"percentage_owned":"50.0","net_equity":"47000.0","main_home_equity_disregard":"100000.0","assessed_equity":"0.0"},"additional_properties":[{"value":"0.0","transaction_allowance":"0.0","allowable_outstanding_mortgage":"0.0","percentage_owned":"0.0","assessed_equity":"0.0"}]},"vehicles":{"total_vehicle":"0.0","vehicles":[]}}'
    http_version: null
  recorded_at: Thu, 05 Mar 2020 15:38:16 GMT
recorded_with: VCR 5.1.0
