---
http_interactions:
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments
    body:
      encoding: UTF-8
      string: '{"client_reference_id":"L-UHT-BHU","submission_date":"2020-03-05","matter_proceeding_type":"domestic_abuse"}'
    headers:
      User-Agent:
      - Faraday v0.17.3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - openresty/1.15.8.2
      Date:
      - Thu, 05 Mar 2020 15:36:45 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Etag:
      - W/"aeb21dd8d6c51740c1dddf2bc422c7b7"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 9893931660866eb7864c66e382aa62f6
      X-Runtime:
      - '0.076840'
    body:
      encoding: ASCII-8BIT
      string: '{"success":true,"objects":[{"id":"656aad34-cab7-41e4-9a22-ae5ddb629dd2","client_reference_id":"L-UHT-BHU","remote_ip":{"family":2,"addr":1377660346,"mask_addr":4294967295},"created_at":"2020-03-05T15:36:45.261Z","updated_at":"2020-03-05T15:36:45.261Z","submission_date":"2020-03-05","matter_proceeding_type":"domestic_abuse","assessment_result":"pending"}],"errors":[]}'
    http_version: null
  recorded_at: Thu, 05 Mar 2020 15:36:45 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/656aad34-cab7-41e4-9a22-ae5ddb629dd2/applicant
    body:
      encoding: UTF-8
      string: '{"applicant":{"date_of_birth":"1980-01-10","involvement_type":"applicant","has_partner_opponent":false,"receives_qualifying_benefit":true}}'
    headers:
      User-Agent:
      - Faraday v0.17.3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - openresty/1.15.8.2
      Date:
      - Thu, 05 Mar 2020 15:36:45 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Etag:
      - W/"efb4e823dbce2ccd2cf2dff7d7ee9c34"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - ecf64e5da7593ecc0666fbe19a9e1d87
      X-Runtime:
      - '0.047633'
    body:
      encoding: ASCII-8BIT
      string: '{"objects":[{"id":"793e6e67-7b66-4981-90dd-b5ed7c0d3657","assessment_id":"656aad34-cab7-41e4-9a22-ae5ddb629dd2","date_of_birth":"1980-01-10","involvement_type":"applicant","has_partner_opponent":false,"receives_qualifying_benefit":true,"created_at":"2020-03-05T15:36:45.437Z","updated_at":"2020-03-05T15:36:45.437Z","self_employed":false}],"errors":[],"success":true}'
    http_version: null
  recorded_at: Thu, 05 Mar 2020 15:36:45 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/656aad34-cab7-41e4-9a22-ae5ddb629dd2/capitals
    body:
      encoding: UTF-8
      string: '{"bank_accounts":[{"description":"Money not in a bank account","value":"10000.0"}],"non_liquid_capital":[{"description":"Land","value":"50000.0"}]}'
    headers:
      User-Agent:
      - Faraday v0.17.3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - openresty/1.15.8.2
      Date:
      - Thu, 05 Mar 2020 15:36:45 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Etag:
      - W/"c3bd438e4985e6f7e18ec87eb65e1578"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - d794ce59a38081bc43e228ec60c4c8c5
      X-Runtime:
      - '0.012855'
    body:
      encoding: ASCII-8BIT
      string: '{"objects":{"id":"6c710233-1507-4d20-a102-036d9bc6e554","assessment_id":"656aad34-cab7-41e4-9a22-ae5ddb629dd2","total_liquid":"0.0","total_non_liquid":"0.0","total_vehicle":"0.0","total_property":"0.0","total_mortgage_allowance":"0.0","total_capital":"0.0","pensioner_capital_disregard":"0.0","assessed_capital":"0.0","capital_contribution":"0.0","lower_threshold":"0.0","upper_threshold":"0.0","assessment_result":"pending","created_at":"2020-03-05T15:36:45.264Z","updated_at":"2020-03-05T15:36:45.264Z"},"errors":[],"success":true}'
    http_version: null
  recorded_at: Thu, 05 Mar 2020 15:36:45 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/656aad34-cab7-41e4-9a22-ae5ddb629dd2/vehicles
    body:
      encoding: UTF-8
      string: '{"vehicles":[]}'
    headers:
      User-Agent:
      - Faraday v0.17.3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - openresty/1.15.8.2
      Date:
      - Thu, 05 Mar 2020 15:36:45 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Etag:
      - W/"7eb7dee5a8f69a7b4580e1e2bd9fa86a"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 28eec3b9d54b1b8a0a5fa0db66c57f0e
      X-Runtime:
      - '0.004561'
    body:
      encoding: ASCII-8BIT
      string: '{"vehicles":[],"errors":[],"success":true}'
    http_version: null
  recorded_at: Thu, 05 Mar 2020 15:36:45 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/656aad34-cab7-41e4-9a22-ae5ddb629dd2/properties
    body:
      encoding: UTF-8
      string: '{"properties":{"main_home":{"value":"200000.0","outstanding_mortgage":"100000.0","percentage_owned":"50.0","shared_with_housing_assoc":false},"additional_properties":[{"value":0,"outstanding_mortgage":0,"percentage_owned":0,"shared_with_housing_assoc":false}]}}'
    headers:
      User-Agent:
      - Faraday v0.17.3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - openresty/1.15.8.2
      Date:
      - Thu, 05 Mar 2020 15:36:45 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Etag:
      - W/"0fe0f0708604c261b7d93dc47ebecd73"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 2d067f0c3fb8e3acd6ebecdeddc3e5f8
      X-Runtime:
      - '0.016182'
    body:
      encoding: ASCII-8BIT
      string: '{"objects":[{"id":"e6e6a639-6f37-45e6-96a2-bdfe3d8059eb","value":"200000.0","outstanding_mortgage":"100000.0","percentage_owned":"50.0","main_home":true,"shared_with_housing_assoc":false,"created_at":"2020-03-05T15:36:45.807Z","updated_at":"2020-03-05T15:36:45.807Z","capital_summary_id":"6c710233-1507-4d20-a102-036d9bc6e554","transaction_allowance":"0.0","allowable_outstanding_mortgage":"0.0","net_value":"0.0","net_equity":"0.0","assessed_equity":"0.0","main_home_equity_disregard":"0.0"},{"id":"ba54a751-843c-4818-b1f5-6840f2559128","value":"0.0","outstanding_mortgage":"0.0","percentage_owned":"0.0","main_home":false,"shared_with_housing_assoc":false,"created_at":"2020-03-05T15:36:45.812Z","updated_at":"2020-03-05T15:36:45.812Z","capital_summary_id":"6c710233-1507-4d20-a102-036d9bc6e554","transaction_allowance":"0.0","allowable_outstanding_mortgage":"0.0","net_value":"0.0","net_equity":"0.0","assessed_equity":"0.0","main_home_equity_disregard":"0.0"}],"errors":[],"success":true}'
    http_version: null
  recorded_at: Thu, 05 Mar 2020 15:36:45 GMT
- request:
    method: get
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/656aad34-cab7-41e4-9a22-ae5ddb629dd2
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.17.3
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - openresty/1.15.8.2
      Date:
      - Thu, 05 Mar 2020 15:36:45 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Etag:
      - W/"ea7f29fa55fe6f3e0292ca8e57e55eb4"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 42ac58daca197290e303fb8d1df38ced
      X-Runtime:
      - '0.072088'
    body:
      encoding: ASCII-8BIT
      string: '{"assessment_result":"contribution_required","applicant":{"receives_qualifying_benefit":true,"age_at_submission":40},"capital":{"total_liquid":"10000.0","total_non_liquid":"50000.0","pensioner_capital_disregard":"0.0","total_capital":"60000.0","capital_contribution":"57000.0","liquid_capital_items":[{"description":"Money
        not in a bank account","value":"10000.0"}],"non_liquid_capital_items":[{"description":"Land","value":"50000.0"}]},"property":{"total_mortgage_allowance":"100000.0","total_property":"0.0","main_home":{"value":"200000.0","transaction_allowance":"6000.0","allowable_outstanding_mortgage":"100000.0","shared_with_housing_assoc":false,"percentage_owned":"50.0","net_equity":"47000.0","main_home_equity_disregard":"100000.0","assessed_equity":"0.0"},"additional_properties":[{"value":"0.0","transaction_allowance":"0.0","allowable_outstanding_mortgage":"0.0","percentage_owned":"0.0","assessed_equity":"0.0"}]},"vehicles":{"total_vehicle":"0.0","vehicles":[]}}'
    http_version: null
  recorded_at: Thu, 05 Mar 2020 15:36:46 GMT
recorded_with: VCR 5.1.0
