---
http_interactions:
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments
    body:
      encoding: UTF-8
      string: '{"client_reference_id":"L-U6D-15H","submission_date":"2020-05-29","matter_proceeding_type":"domestic_abuse"}'
    headers:
      Content-Type:
      - application/json
      User-Agent:
      - Faraday v1.0.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - nginx/1.17.8
      Date:
      - Fri, 29 May 2020 14:12:00 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Etag:
      - W/"ddf52515750745c7b9fff9c60d5e65b4"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - f1404e898f522569f52a206ecca4e087
      X-Runtime:
      - '0.064293'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
    body:
      encoding: ASCII-8BIT
      string: '{"success":true,"objects":[{"id":"159003ba-df75-4015-82de-a79f36d82113","client_reference_id":"L-U6D-15H","remote_ip":{"family":2,"addr":1367788061,"mask_addr":4294967295},"created_at":"2020-05-29T14:12:00.876Z","updated_at":"2020-05-29T14:12:00.876Z","submission_date":"2020-05-29","matter_proceeding_type":"domestic_abuse","assessment_result":"pending","remarks":{}}],"assessment_id":"159003ba-df75-4015-82de-a79f36d82113","errors":[]}'
  recorded_at: Fri, 29 May 2020 14:12:00 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/159003ba-df75-4015-82de-a79f36d82113/applicant
    body:
      encoding: UTF-8
      string: '{"applicant":{"date_of_birth":"1963-05-22","involvement_type":"applicant","has_partner_opponent":false,"receives_qualifying_benefit":false}}'
    headers:
      Content-Type:
      - application/json
      User-Agent:
      - Faraday v1.0.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - nginx/1.17.8
      Date:
      - Fri, 29 May 2020 14:12:01 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Etag:
      - W/"e156c1de751f0fc41f3ce5edefd256d2"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - d0542b9b8ac69c9f5ccd1dbaec392c24
      X-Runtime:
      - '0.067461'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
    body:
      encoding: ASCII-8BIT
      string: '{"success":true,"errors":[]}'
  recorded_at: Fri, 29 May 2020 14:12:01 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/159003ba-df75-4015-82de-a79f36d82113/capitals
    body:
      encoding: UTF-8
      string: '{"bank_accounts":[],"non_liquid_capital":[]}'
    headers:
      Content-Type:
      - application/json
      User-Agent:
      - Faraday v1.0.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - nginx/1.17.8
      Date:
      - Fri, 29 May 2020 14:12:01 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Etag:
      - W/"e156c1de751f0fc41f3ce5edefd256d2"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 8ee4c35dc55d2787016f89d80f123a52
      X-Runtime:
      - '0.051445'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
    body:
      encoding: ASCII-8BIT
      string: '{"success":true,"errors":[]}'
  recorded_at: Fri, 29 May 2020 14:12:01 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/159003ba-df75-4015-82de-a79f36d82113/vehicles
    body:
      encoding: UTF-8
      string: '{"vehicles":[]}'
    headers:
      Content-Type:
      - application/json
      User-Agent:
      - Faraday v1.0.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - nginx/1.17.8
      Date:
      - Fri, 29 May 2020 14:12:01 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Etag:
      - W/"e156c1de751f0fc41f3ce5edefd256d2"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - b912d7ae6c486be6417971d7fea2c168
      X-Runtime:
      - '0.064140'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
    body:
      encoding: ASCII-8BIT
      string: '{"success":true,"errors":[]}'
  recorded_at: Fri, 29 May 2020 14:12:01 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/159003ba-df75-4015-82de-a79f36d82113/properties
    body:
      encoding: UTF-8
      string: '{"properties":{"main_home":{"value":0.0,"outstanding_mortgage":0.0,"percentage_owned":0.0,"shared_with_housing_assoc":false},"additional_properties":[{"value":0,"outstanding_mortgage":0,"percentage_owned":0,"shared_with_housing_assoc":false}]}}'
    headers:
      Content-Type:
      - application/json
      User-Agent:
      - Faraday v1.0.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - nginx/1.17.8
      Date:
      - Fri, 29 May 2020 14:12:02 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Etag:
      - W/"e156c1de751f0fc41f3ce5edefd256d2"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 17f56c8b5e3602fe16a999b859113dd8
      X-Runtime:
      - '0.065138'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
    body:
      encoding: ASCII-8BIT
      string: '{"success":true,"errors":[]}'
  recorded_at: Fri, 29 May 2020 14:12:02 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/159003ba-df75-4015-82de-a79f36d82113/dependants
    body:
      encoding: UTF-8
      string: '{"dependants":[]}'
    headers:
      Content-Type:
      - application/json
      User-Agent:
      - Faraday v1.0.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - nginx/1.17.8
      Date:
      - Fri, 29 May 2020 14:12:02 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Etag:
      - W/"e156c1de751f0fc41f3ce5edefd256d2"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - f9af1aa63128a8bd63ffbe42241f546b
      X-Runtime:
      - '0.097454'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
    body:
      encoding: ASCII-8BIT
      string: '{"success":true,"errors":[]}'
  recorded_at: Fri, 29 May 2020 14:12:02 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/159003ba-df75-4015-82de-a79f36d82113/outgoings
    body:
      encoding: UTF-8
      string: '{"outgoings":[]}'
    headers:
      Content-Type:
      - application/json
      User-Agent:
      - Faraday v1.0.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - nginx/1.17.8
      Date:
      - Fri, 29 May 2020 14:12:02 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Etag:
      - W/"e156c1de751f0fc41f3ce5edefd256d2"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - d92a33ff76d6ee18cf3f3ec6b7ecb490
      X-Runtime:
      - '0.002515'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
    body:
      encoding: ASCII-8BIT
      string: '{"success":true,"errors":[]}'
  recorded_at: Fri, 29 May 2020 14:12:02 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/159003ba-df75-4015-82de-a79f36d82113/state_benefits
    body:
      encoding: UTF-8
      string: '{"state_benefits":[{"name":"Child Benefit","payments":[{"date":"2020-02-29","amount":534049.09,"client_id":"93d69266-239e-44cd-847e-680b36750814"},{"date":"2020-03-30","amount":178415.31,"client_id":"c78eb87a-0549-4412-a816-5c2f459f5ae0"},{"date":"2020-04-29","amount":942231.17,"client_id":"d75c957f-aa5a-4dfd-a05e-01a47087f564"}]}]}'
    headers:
      Content-Type:
      - application/json
      User-Agent:
      - Faraday v1.0.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - nginx/1.17.8
      Date:
      - Fri, 29 May 2020 14:12:03 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Etag:
      - W/"e156c1de751f0fc41f3ce5edefd256d2"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - f85b7120a6dd0f97504781562e765a37
      X-Runtime:
      - '0.098473'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
    body:
      encoding: ASCII-8BIT
      string: '{"success":true,"errors":[]}'
  recorded_at: Fri, 29 May 2020 14:12:03 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/159003ba-df75-4015-82de-a79f36d82113/other_incomes
    body:
      encoding: UTF-8
      string: '{"other_incomes":[]}'
    headers:
      Content-Type:
      - application/json
      User-Agent:
      - Faraday v1.0.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - nginx/1.17.8
      Date:
      - Fri, 29 May 2020 14:12:03 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Etag:
      - W/"e156c1de751f0fc41f3ce5edefd256d2"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 15b0e6171aaac5ae296cf3bacba4f221
      X-Runtime:
      - '0.051128'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
    body:
      encoding: ASCII-8BIT
      string: '{"success":true,"errors":[]}'
  recorded_at: Fri, 29 May 2020 14:12:03 GMT
- request:
    method: get
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/159003ba-df75-4015-82de-a79f36d82113
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Content-Type:
      - application/json
      Accept:
      - application/json;version=2
      User-Agent:
      - Faraday v1.0.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - nginx/1.17.8
      Date:
      - Fri, 29 May 2020 14:12:03 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Etag:
      - W/"0ea5853bd92d0dd5432e99136def6c78"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 17c8d816a1c5b81e1e9205344e7b5934
      X-Runtime:
      - '0.210395'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
    body:
      encoding: ASCII-8BIT
      string: '{"version":"2","timestamp":"2020-05-29T14:12:03.842+00:00","success":true,"assessment":{"id":"159003ba-df75-4015-82de-a79f36d82113","client_reference_id":"L-U6D-15H","submission_date":"2020-05-29","matter_proceeding_type":"domestic_abuse","assessment_result":"contribution_required","applicant":{"date_of_birth":"1963-05-22","involvement_type":"applicant","has_partner_opponent":false,"receives_qualifying_benefit":false,"self_employed":false},"gross_income":{"monthly_other_income":"0.0","monthly_state_benefits":"551565.19","total_gross_income":"551565.19","upper_threshold":"999999999999.0","assessment_result":"eligible","monthly_income_equivalents":{"friends_or_family":"0.0","maintenance_in":"0.0","property_or_lodger":"0.0","student_loan":"0.0","pension":"0.0"},"monthly_outgoing_equivalents":{"child_care":"0.0","maintenance_out":"0.0","rent_or_mortgage":"0.0","legal_aid":"0.0"},"state_benefits":[{"name":"Child
        Benefit","monthly_value":"551565.19","excluded_from_income_assessment":false,"state_benefit_payments":[{"payment_date":"2020-04-29","amount":"942231.17"},{"payment_date":"2020-03-30","amount":"178415.31"},{"payment_date":"2020-02-29","amount":"534049.09"}]}],"other_income":[]},"disposable_income":{"monthly_outgoing_equivalents":{"child_care":"0.0","maintenance_out":"0.0","rent_or_mortgage":"0.0","legal_aid":"0.0"},"childcare_allowance":"0.0","deductions":{"dependants_allowance":"0.0","disregarded_state_benefits":0.0},"dependant_allowance":"0.0","maintenance_allowance":"0.0","gross_housing_costs":"0.0","housing_benefit":"0.0","net_housing_costs":"0.0","total_outgoings_and_allowances":"0.0","total_disposable_income":"551565.19","lower_threshold":"315.0","upper_threshold":"999999999999.0","assessment_result":"contribution_required","income_contribution":"385786.28"},"capital":{"capital_items":{"liquid":[],"non_liquid":[],"vehicles":[],"properties":{"main_home":{"value":"0.0","outstanding_mortgage":"0.0","percentage_owned":"0.0","main_home":true,"shared_with_housing_assoc":false,"transaction_allowance":"0.0","allowable_outstanding_mortgage":"0.0","net_value":"0.0","net_equity":"0.0","main_home_equity_disregard":"100000.0","assessed_equity":"0.0"},"additional_properties":[{"value":"0.0","outstanding_mortgage":"0.0","percentage_owned":"0.0","main_home":false,"shared_with_housing_assoc":false,"transaction_allowance":"0.0","allowable_outstanding_mortgage":"0.0","net_value":"0.0","net_equity":"0.0","main_home_equity_disregard":"0.0","assessed_equity":"0.0"}]}},"total_liquid":"0.0","total_non_liquid":"0.0","total_vehicle":"0.0","total_property":"0.0","total_mortgage_allowance":"100000.0","total_capital":"0.0","pensioner_capital_disregard":"0.0","assessed_capital":"0.0","lower_threshold":"3000.0","upper_threshold":"999999999999.0","assessment_result":"eligible","capital_contribution":"0.0"},"remarks":{"state_benefit_payment":{"amount_variation":["d75c957f-aa5a-4dfd-a05e-01a47087f564","c78eb87a-0549-4412-a816-5c2f459f5ae0","93d69266-239e-44cd-847e-680b36750814"]}}}}'
  recorded_at: Fri, 29 May 2020 14:12:03 GMT
recorded_with: VCR 6.0.0
