---
http_interactions:
- request:
    method: get
    uri: https://api.ordnancesurvey.co.uk/places/v1/addresses/postcode?key=OvltQCeDASvuxteFuyaScEhO6GTKq05d&postcode=DA74NG
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.2
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Type:
      - application/json;charset=UTF-8
      Date:
      - Tue, 30 Oct 2018 10:16:40 GMT
      Server:
      - Apache-Coyote/1.1
      Status:
      - success
      Tx-Id:
      - 1540894600473:473
      Content-Length:
      - '11442'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: |-
        {
          "header" : {
            "uri" : "https://api.ordnancesurvey.co.uk/places/v1/addresses/postcode?postcode=DA74NG",
            "query" : "postcode=DA74NG",
            "offset" : 0,
            "totalresults" : 11,
            "format" : "JSON",
            "dataset" : "DPA",
            "lr" : "EN,CY",
            "maxresults" : 100,
            "epoch" : "61",
            "output_srs" : "EPSG:27700"
          },
          "results" : [ {
            "DPA" : {
              "UPRN" : "100020211558",
              "UDPRN" : "6248161",
              "ADDRESS" : "1, LONSDALE ROAD, BEXLEYHEATH, DA7 4NG",
              "BUILDING_NUMBER" : "1",
              "THOROUGHFARE_NAME" : "LONSDALE ROAD",
              "POST_TOWN" : "BEXLEYHEATH",
              "POSTCODE" : "DA7 4NG",
              "RPC" : "1",
              "X_COORDINATE" : 548894.0,
              "Y_COORDINATE" : 176139.0,
              "STATUS" : "APPROVED",
              "LOGICAL_STATUS_CODE" : "1",
              "CLASSIFICATION_CODE" : "RD02",
              "CLASSIFICATION_CODE_DESCRIPTION" : "Detached",
              "LOCAL_CUSTODIAN_CODE" : 5120,
              "LOCAL_CUSTODIAN_CODE_DESCRIPTION" : "BEXLEY",
              "POSTAL_ADDRESS_CODE" : "D",
              "POSTAL_ADDRESS_CODE_DESCRIPTION" : "A record which is linked to PAF",
              "BLPU_STATE_CODE_DESCRIPTION" : "Unknown/Not applicable",
              "TOPOGRAPHY_LAYER_TOID" : "osgb1000000095093",
              "LAST_UPDATE_DATE" : "10/02/2016",
              "ENTRY_DATE" : "19/03/2001",
              "LANGUAGE" : "EN",
              "MATCH" : 1.0,
              "MATCH_DESCRIPTION" : "EXACT"
            }
          }, {
            "DPA" : {
              "UPRN" : "100020211559",
              "UDPRN" : "6248164",
              "ADDRESS" : "2, LONSDALE ROAD, BEXLEYHEATH, DA7 4NG",
              "BUILDING_NUMBER" : "2",
              "THOROUGHFARE_NAME" : "LONSDALE ROAD",
              "POST_TOWN" : "BEXLEYHEATH",
              "POSTCODE" : "DA7 4NG",
              "RPC" : "1",
              "X_COORDINATE" : 548861.0,
              "Y_COORDINATE" : 176156.0,
              "STATUS" : "APPROVED",
              "LOGICAL_STATUS_CODE" : "1",
              "CLASSIFICATION_CODE" : "RD03",
              "CLASSIFICATION_CODE_DESCRIPTION" : "Semi-Detached",
              "LOCAL_CUSTODIAN_CODE" : 5120,
              "LOCAL_CUSTODIAN_CODE_DESCRIPTION" : "BEXLEY",
              "POSTAL_ADDRESS_CODE" : "D",
              "POSTAL_ADDRESS_CODE_DESCRIPTION" : "A record which is linked to PAF",
              "BLPU_STATE_CODE_DESCRIPTION" : "Unknown/Not applicable",
              "TOPOGRAPHY_LAYER_TOID" : "osgb1000000095079",
              "LAST_UPDATE_DATE" : "10/02/2016",
              "ENTRY_DATE" : "04/06/2005",
              "LANGUAGE" : "EN",
              "MATCH" : 1.0,
              "MATCH_DESCRIPTION" : "EXACT"
            }
          }, {
            "DPA" : {
              "UPRN" : "100020211560",
              "UDPRN" : "6248165",
              "ADDRESS" : "3, LONSDALE ROAD, BEXLEYHEATH, DA7 4NG",
              "BUILDING_NUMBER" : "3",
              "THOROUGHFARE_NAME" : "LONSDALE ROAD",
              "POST_TOWN" : "BEXLEYHEATH",
              "POSTCODE" : "DA7 4NG",
              "RPC" : "1",
              "X_COORDINATE" : 548888.0,
              "Y_COORDINATE" : 176131.0,
              "STATUS" : "APPROVED",
              "LOGICAL_STATUS_CODE" : "1",
              "CLASSIFICATION_CODE" : "RD02",
              "CLASSIFICATION_CODE_DESCRIPTION" : "Detached",
              "LOCAL_CUSTODIAN_CODE" : 5120,
              "LOCAL_CUSTODIAN_CODE_DESCRIPTION" : "BEXLEY",
              "POSTAL_ADDRESS_CODE" : "D",
              "POSTAL_ADDRESS_CODE_DESCRIPTION" : "A record which is linked to PAF",
              "BLPU_STATE_CODE_DESCRIPTION" : "Unknown/Not applicable",
              "TOPOGRAPHY_LAYER_TOID" : "osgb5000005153955102",
              "LAST_UPDATE_DATE" : "10/02/2016",
              "ENTRY_DATE" : "04/06/2005",
              "LANGUAGE" : "EN",
              "MATCH" : 1.0,
              "MATCH_DESCRIPTION" : "EXACT"
            }
          }, {
            "DPA" : {
              "UPRN" : "100020211561",
              "UDPRN" : "6248166",
              "ADDRESS" : "4, LONSDALE ROAD, BEXLEYHEATH, DA7 4NG",
              "BUILDING_NUMBER" : "4",
              "THOROUGHFARE_NAME" : "LONSDALE ROAD",
              "POST_TOWN" : "BEXLEYHEATH",
              "POSTCODE" : "DA7 4NG",
              "RPC" : "1",
              "X_COORDINATE" : 548858.0,
              "Y_COORDINATE" : 176150.0,
              "STATUS" : "APPROVED",
              "LOGICAL_STATUS_CODE" : "1",
              "CLASSIFICATION_CODE" : "RD03",
              "CLASSIFICATION_CODE_DESCRIPTION" : "Semi-Detached",
              "LOCAL_CUSTODIAN_CODE" : 5120,
              "LOCAL_CUSTODIAN_CODE_DESCRIPTION" : "BEXLEY",
              "POSTAL_ADDRESS_CODE" : "D",
              "POSTAL_ADDRESS_CODE_DESCRIPTION" : "A record which is linked to PAF",
              "BLPU_STATE_CODE_DESCRIPTION" : "Unknown/Not applicable",
              "TOPOGRAPHY_LAYER_TOID" : "osgb1000000095080",
              "LAST_UPDATE_DATE" : "10/02/2016",
              "ENTRY_DATE" : "19/03/2001",
              "LANGUAGE" : "EN",
              "MATCH" : 1.0,
              "MATCH_DESCRIPTION" : "EXACT"
            }
          }, {
            "DPA" : {
              "UPRN" : "100020211562",
              "UDPRN" : "6248167",
              "ADDRESS" : "5, LONSDALE ROAD, BEXLEYHEATH, DA7 4NG",
              "BUILDING_NUMBER" : "5",
              "THOROUGHFARE_NAME" : "LONSDALE ROAD",
              "POST_TOWN" : "BEXLEYHEATH",
              "POSTCODE" : "DA7 4NG",
              "RPC" : "1",
              "X_COORDINATE" : 548884.0,
              "Y_COORDINATE" : 176118.0,
              "STATUS" : "APPROVED",
              "LOGICAL_STATUS_CODE" : "1",
              "CLASSIFICATION_CODE" : "RD02",
              "CLASSIFICATION_CODE_DESCRIPTION" : "Detached",
              "LOCAL_CUSTODIAN_CODE" : 5120,
              "LOCAL_CUSTODIAN_CODE_DESCRIPTION" : "BEXLEY",
              "POSTAL_ADDRESS_CODE" : "D",
              "POSTAL_ADDRESS_CODE_DESCRIPTION" : "A record which is linked to PAF",
              "BLPU_STATE_CODE_DESCRIPTION" : "Unknown/Not applicable",
              "TOPOGRAPHY_LAYER_TOID" : "osgb1000000095091",
              "LAST_UPDATE_DATE" : "10/02/2016",
              "ENTRY_DATE" : "19/03/2001",
              "LANGUAGE" : "EN",
              "MATCH" : 1.0,
              "MATCH_DESCRIPTION" : "EXACT"
            }
          }, {
            "DPA" : {
              "UPRN" : "100020211563",
              "UDPRN" : "6248168",
              "ADDRESS" : "6, LONSDALE ROAD, BEXLEYHEATH, DA7 4NG",
              "BUILDING_NUMBER" : "6",
              "THOROUGHFARE_NAME" : "LONSDALE ROAD",
              "POST_TOWN" : "BEXLEYHEATH",
              "POSTCODE" : "DA7 4NG",
              "RPC" : "1",
              "X_COORDINATE" : 548849.0,
              "Y_COORDINATE" : 176141.0,
              "STATUS" : "APPROVED",
              "LOGICAL_STATUS_CODE" : "1",
              "CLASSIFICATION_CODE" : "RD03",
              "CLASSIFICATION_CODE_DESCRIPTION" : "Semi-Detached",
              "LOCAL_CUSTODIAN_CODE" : 5120,
              "LOCAL_CUSTODIAN_CODE_DESCRIPTION" : "BEXLEY",
              "POSTAL_ADDRESS_CODE" : "D",
              "POSTAL_ADDRESS_CODE_DESCRIPTION" : "A record which is linked to PAF",
              "BLPU_STATE_CODE_DESCRIPTION" : "Unknown/Not applicable",
              "TOPOGRAPHY_LAYER_TOID" : "osgb1000000095082",
              "LAST_UPDATE_DATE" : "10/02/2016",
              "ENTRY_DATE" : "04/06/2005",
              "LANGUAGE" : "EN",
              "MATCH" : 1.0,
              "MATCH_DESCRIPTION" : "EXACT"
            }
          }, {
            "DPA" : {
              "UPRN" : "100020211564",
              "UDPRN" : "6248169",
              "ADDRESS" : "7, LONSDALE ROAD, BEXLEYHEATH, DA7 4NG",
              "BUILDING_NUMBER" : "7",
              "THOROUGHFARE_NAME" : "LONSDALE ROAD",
              "POST_TOWN" : "BEXLEYHEATH",
              "POSTCODE" : "DA7 4NG",
              "RPC" : "1",
              "X_COORDINATE" : 548874.0,
              "Y_COORDINATE" : 176106.0,
              "STATUS" : "APPROVED",
              "LOGICAL_STATUS_CODE" : "1",
              "CLASSIFICATION_CODE" : "RD03",
              "CLASSIFICATION_CODE_DESCRIPTION" : "Semi-Detached",
              "LOCAL_CUSTODIAN_CODE" : 5120,
              "LOCAL_CUSTODIAN_CODE_DESCRIPTION" : "BEXLEY",
              "POSTAL_ADDRESS_CODE" : "D",
              "POSTAL_ADDRESS_CODE_DESCRIPTION" : "A record which is linked to PAF",
              "BLPU_STATE_CODE_DESCRIPTION" : "Unknown/Not applicable",
              "TOPOGRAPHY_LAYER_TOID" : "osgb1000000095089",
              "LAST_UPDATE_DATE" : "10/02/2016",
              "ENTRY_DATE" : "19/03/2001",
              "LANGUAGE" : "EN",
              "MATCH" : 1.0,
              "MATCH_DESCRIPTION" : "EXACT"
            }
          }, {
            "DPA" : {
              "UPRN" : "100020211565",
              "UDPRN" : "6248170",
              "ADDRESS" : "8, LONSDALE ROAD, BEXLEYHEATH, DA7 4NG",
              "BUILDING_NUMBER" : "8",
              "THOROUGHFARE_NAME" : "LONSDALE ROAD",
              "POST_TOWN" : "BEXLEYHEATH",
              "POSTCODE" : "DA7 4NG",
              "RPC" : "1",
              "X_COORDINATE" : 548846.0,
              "Y_COORDINATE" : 176133.0,
              "STATUS" : "APPROVED",
              "LOGICAL_STATUS_CODE" : "1",
              "CLASSIFICATION_CODE" : "RD03",
              "CLASSIFICATION_CODE_DESCRIPTION" : "Semi-Detached",
              "LOCAL_CUSTODIAN_CODE" : 5120,
              "LOCAL_CUSTODIAN_CODE_DESCRIPTION" : "BEXLEY",
              "POSTAL_ADDRESS_CODE" : "D",
              "POSTAL_ADDRESS_CODE_DESCRIPTION" : "A record which is linked to PAF",
              "BLPU_STATE_CODE_DESCRIPTION" : "Unknown/Not applicable",
              "TOPOGRAPHY_LAYER_TOID" : "osgb1000000095083",
              "LAST_UPDATE_DATE" : "10/02/2016",
              "ENTRY_DATE" : "04/06/2005",
              "LANGUAGE" : "EN",
              "MATCH" : 1.0,
              "MATCH_DESCRIPTION" : "EXACT"
            }
          }, {
            "DPA" : {
              "UPRN" : "100020211566",
              "UDPRN" : "6248171",
              "ADDRESS" : "9, LONSDALE ROAD, BEXLEYHEATH, DA7 4NG",
              "BUILDING_NUMBER" : "9",
              "THOROUGHFARE_NAME" : "LONSDALE ROAD",
              "POST_TOWN" : "BEXLEYHEATH",
              "POSTCODE" : "DA7 4NG",
              "RPC" : "1",
              "X_COORDINATE" : 548868.0,
              "Y_COORDINATE" : 176104.0,
              "STATUS" : "APPROVED",
              "LOGICAL_STATUS_CODE" : "1",
              "CLASSIFICATION_CODE" : "RD03",
              "CLASSIFICATION_CODE_DESCRIPTION" : "Semi-Detached",
              "LOCAL_CUSTODIAN_CODE" : 5120,
              "LOCAL_CUSTODIAN_CODE_DESCRIPTION" : "BEXLEY",
              "POSTAL_ADDRESS_CODE" : "D",
              "POSTAL_ADDRESS_CODE_DESCRIPTION" : "A record which is linked to PAF",
              "BLPU_STATE_CODE_DESCRIPTION" : "Unknown/Not applicable",
              "TOPOGRAPHY_LAYER_TOID" : "osgb1000000095088",
              "LAST_UPDATE_DATE" : "10/02/2016",
              "ENTRY_DATE" : "04/06/2005",
              "LANGUAGE" : "EN",
              "MATCH" : 1.0,
              "MATCH_DESCRIPTION" : "EXACT"
            }
          }, {
            "DPA" : {
              "UPRN" : "100020211567",
              "UDPRN" : "6248162",
              "ADDRESS" : "10, LONSDALE ROAD, BEXLEYHEATH, DA7 4NG",
              "BUILDING_NUMBER" : "10",
              "THOROUGHFARE_NAME" : "LONSDALE ROAD",
              "POST_TOWN" : "BEXLEYHEATH",
              "POSTCODE" : "DA7 4NG",
              "RPC" : "1",
              "X_COORDINATE" : 548848.0,
              "Y_COORDINATE" : 176115.0,
              "STATUS" : "APPROVED",
              "LOGICAL_STATUS_CODE" : "1",
              "CLASSIFICATION_CODE" : "RD03",
              "CLASSIFICATION_CODE_DESCRIPTION" : "Semi-Detached",
              "LOCAL_CUSTODIAN_CODE" : 5120,
              "LOCAL_CUSTODIAN_CODE_DESCRIPTION" : "BEXLEY",
              "POSTAL_ADDRESS_CODE" : "D",
              "POSTAL_ADDRESS_CODE_DESCRIPTION" : "A record which is linked to PAF",
              "BLPU_STATE_CODE_DESCRIPTION" : "Unknown/Not applicable",
              "TOPOGRAPHY_LAYER_TOID" : "osgb1000000095085",
              "LAST_UPDATE_DATE" : "10/02/2016",
              "ENTRY_DATE" : "04/06/2005",
              "LANGUAGE" : "EN",
              "MATCH" : 1.0,
              "MATCH_DESCRIPTION" : "EXACT"
            }
          }, {
            "DPA" : {
              "UPRN" : "100020211568",
              "UDPRN" : "6248163",
              "ADDRESS" : "12, LONSDALE ROAD, BEXLEYHEATH, DA7 4NG",
              "BUILDING_NUMBER" : "12",
              "THOROUGHFARE_NAME" : "LONSDALE ROAD",
              "POST_TOWN" : "BEXLEYHEATH",
              "POSTCODE" : "DA7 4NG",
              "RPC" : "1",
              "X_COORDINATE" : 548854.0,
              "Y_COORDINATE" : 176110.0,
              "STATUS" : "APPROVED",
              "LOGICAL_STATUS_CODE" : "1",
              "CLASSIFICATION_CODE" : "RD03",
              "CLASSIFICATION_CODE_DESCRIPTION" : "Semi-Detached",
              "LOCAL_CUSTODIAN_CODE" : 5120,
              "LOCAL_CUSTODIAN_CODE_DESCRIPTION" : "BEXLEY",
              "POSTAL_ADDRESS_CODE" : "D",
              "POSTAL_ADDRESS_CODE_DESCRIPTION" : "A record which is linked to PAF",
              "BLPU_STATE_CODE_DESCRIPTION" : "Unknown/Not applicable",
              "TOPOGRAPHY_LAYER_TOID" : "osgb1000000095086",
              "LAST_UPDATE_DATE" : "10/02/2016",
              "ENTRY_DATE" : "04/06/2005",
              "LANGUAGE" : "EN",
              "MATCH" : 1.0,
              "MATCH_DESCRIPTION" : "EXACT"
            }
          } ]
        }
    http_version: 
  recorded_at: Tue, 30 Oct 2018 10:16:40 GMT
- request:
    method: post
    uri: https://api.notifications.service.gov.uk/v2/notifications/email
    body:
      encoding: UTF-8
      string: '{"email_address":"test@test.com","template_id":"570e1b9d-6238-45fd-b75c-96f2f39db8e9","personalisation":{"application_url":"http://www.example.com/citizens/legal_aid_applications/6d5a2feb-142b-4bb7-ad54-6cd94843bb20","client_name":"Test
        User","ref_number":"6d5a2feb-142b-4bb7-ad54-6cd94843bb20"}}'
    headers:
      User-Agent:
      - NOTIFY-API-RUBY-CLIENT/2.9.0
      Content-Type:
      - application/json
      Authorization:
      - Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjZjgxNmEzNC1mMmJkLTQxMjItOTQ0ZS00YjY4MjhhM2UzNTIiLCJpYXQiOjE1NDA4OTQ2MDF9.oLUe8A-Oc3beyZv3Gmhdj8f4aOzqy5BpJA4FnxGuy_0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 400
      message: Bad Request
    headers:
      Access-Control-Allow-Headers:
      - Content-Type,Authorization
      Access-Control-Allow-Methods:
      - GET,PUT,POST,DELETE
      Access-Control-Allow-Origin:
      - "*"
      Content-Type:
      - application/json
      Date:
      - Tue, 30 Oct 2018 10:16:42 GMT
      Server:
      - nginx
      X-B3-Spanid:
      - dcc91eecb4f7af83
      X-B3-Traceid:
      - dcc91eecb4f7af83
      X-Vcap-Request-Id:
      - 5fd62251-a75d-4549-7ea9-96f0cef09a01
      Content-Length:
      - '90'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"errors":[{"error":"BadRequestError","message":"Template not found"}],"status_code":400}

'
    http_version: 
  recorded_at: Tue, 30 Oct 2018 10:16:42 GMT
recorded_with: VCR 4.0.0
